name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Prepare public directory
        run: |
          # create a minimal public dir containing only static assets
          rm -rf public || true
          mkdir public
          # copy main static files
          cp -R index.html public/ 2>/dev/null || true
          cp -R styles.css public/ 2>/dev/null || true
          cp -R script.js public/ 2>/dev/null || true
          cp -R admin.html public/ 2>/dev/null || true
          cp -R admin.js public/ 2>/dev/null || true
          if [ -d assets ]; then cp -R assets public/; fi
          # copy other useful static files if present
          cp -R README.md public/ 2>/dev/null || true

      - name: Deploy to gh-pages (public dir)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
